### ISSUE TITLE
Error Scanning Containers

### ISSUE THREAD

**Issue by joshuanianji** [joshuanianji/treehouse-bot#98]
An issue with Azure Container Scan (https://github.com/Azure/container-scan/issues/122) means our CI builds are gonna fail a bit until they are fixed.

Not a big deal since this project isn't big.

**Comment by JeffreyArt1** [comment]
Issue is now fixed!

**Comment by joshuanianji** [comment]
Awesome, thanks @JeffreyArt1 !
